### PR TITLE
Fix RootNavigation onReady method

### LINKED ISSUE #170: RootContainer onStateChange causes re-render loop
### Summary

While attempting to integrate [react-naviation screen analytics](https://reactnavigation.org/docs/screen-tracking/) using `onReady` and `onStateChange` on `RootContainer`, I hit the following error:

> Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

After some investigation, it seems calling `RootContainer.useRef()` in the parent component and adding any `onStateChange` method to `<RootContainer/>` causes the parent component to re-render endlessly.

I also noticed the `onReady` handler is not firing. The [only contextProps here](https://github.com/expo/router/blob/main/packages/expo-router/src/ContextNavigationContainer.tsx#L83) are `children`, even if an `onReady` prop is set on `RootContainer`. It seems like the component renders once prior to `setProps` on the `useNavigationContainerContext` context being called, and doesn't update once the context changes.

Any suggestions on how to use the ref from RootContainer within the `onReady` and `onStateChange` handlers?  Would love to integrate screen tracking with expo-router.

Thanks a bunch!

### Minimal reproducible example

```
function RootLayout() {
  const navigationRef = RootContainer.useRef()
  const routeRef = React.useRef()
  console.log('render')
  return (
    <>
    <RootContainer 
      onReady={() => {
        console.log('onReady')    
        routeRef.current = navigationRef?.current?.getCurrentRoute()
      }}
      onStateChange={async () => {
         const previousRoute = routeRef.current
         const currentRoute = navigationRef?.current?.getCurrentRoute()
         if (currentRoute?.name as boolean && previousRoute?.name !== currentRoute?.name) {
           console.log('onStateChange', currentRoute)

         }
        routeRef.current = currentRoute
      }}
    />
      <Layout/>
    </>
  );
}
```

### PR DESCRIPTION
**Pull request by tyrauber**
# Motivation

The contextProps.onReady handler was failing to execute because the RootNavigation onReady method was executing before setProps could set the contextProps, as detailed in #170.

# Execution

This pull request resolves this issue by using the RootNavigation onReady method to setReady, and using a React.useEffect hook to check if contextProps.onReady is present, and if so execute it.  Using contextProps.onReady as a scope on useEffect ensures it only renders once on component render.

```
  React.useEffect(()=>{
    contextProps.onReady?.();
  }, [!!(contextProps?.onReady)])
  ```

Closes #170

# Test Plan

Some console.logs onReady and onState change show they execute, and using `RootContainer.getRef()` no longer causes the infinite render loop.

With this change, react-navigation screen tracking can now be implemented.

```

  const navigationRef = RootContainer.getRef();
  const routeNameRef = useRef();

  return (
    <>
    <RootContainer 
      onReady={(ref) => {
        routeNameRef.current = navigationRef.getCurrentRoute().name;
      }}
      onStateChange={async () => {
        const previousRouteName = routeNameRef.current;
        const currentRouteName = navigationRef.getCurrentRoute().name;

        if (previousRouteName !== currentRouteName) {
          routeNameRef.current = currentRouteName;
          console.log('new route', currentRouteName)
        }
      }}
    />
    ...
    </>
  )
```

### CODE REVIEW

File: packages/expo-router/src/ContextNavigationContainer.tsx [hunk 1]
```diff
@@ -70,6 +70,10 @@ function InternalContextNavigationContainer(props: object) {
     return linking;
   }, [root]);
 
+  React.useEffect(()=>{
+    contextProps.onReady?.();
```
[the remark this answers is not in the document]
Comment (tyrauber) [reply packages/expo-router/src/ContextNavigationContainer.tsx:74]: Hi @EvanBacon, that was the solution I came up with, but I am sure there is a better one.  Let me know if you need any more details on #170.  Happy to test out another approach if you have one.

[the remark this answers is not in the document]
Comment (EvanBacon) [reply packages/expo-router/src/ContextNavigationContainer.tsx:74]: I'm going to merge this, then add a warning not to use onReady per https://github.com/expo/router/issues/170#issuecomment-1369958324

File: packages/expo-router/src/ContextNavigationContainer.tsx [hunk 2]
```diff
@@ -70,6 +70,10 @@ function InternalContextNavigationContainer(props: object) {
     return linking;
   }, [root]);
 
+  React.useEffect(()=>{
```
Comment (EvanBacon) [inline packages/expo-router/src/ContextNavigationContainer.tsx:73]:
```suggestion
  React.useEffect(() => {
```

File: packages/expo-router/src/ContextNavigationContainer.tsx [hunk 3]
```diff
@@ -70,6 +70,10 @@ function InternalContextNavigationContainer(props: object) {
...
+    contextProps.onReady?.();
+  }, [!!(contextProps?.onReady)])
```
Comment (EvanBacon) [inline packages/expo-router/src/ContextNavigationContainer.tsx:75]:
```suggestion
  }, [!!contextProps?.onReady])
```

File: packages/expo-router/src/ContextNavigationContainer.tsx [hunk 4]
```diff
@@ -70,6 +70,10 @@ function InternalContextNavigationContainer(props: object) {
     return linking;
   }, [root]);
 
+  React.useEffect(() => {
+    contextProps.onReady?.();
+  }, [!!contextProps?.onReady])
```
Comment (EvanBacon) [inline packages/expo-router/src/ContextNavigationContainer.tsx:75]:
```suggestion
  }, [!!contextProps?.onReady]);
```
